RNAcentral/rnacentral-webcode

rnacentral/portal/management/commands/xml_exporters/rna2xml.py
Also make sure that HGNC accessions are indexed
Fixes #96
=> Show HGNC entries at the top of search results

rnacentral/portal/management/commands/gpi_export.py, rnacentral/portal/models.py
=> Add miRBase precursors to mature miRNAs in GPI file

rnacentral/portal/templates/portal/about.html, rnacentral/portal/templates/portal/contact.html, rnacentral/portal/templates/portal/expert-database.html, rnacentral/portal/templates/portal/expert-databases.html, rnacentral/portal/templates/portal/help/api-v1.html, rnacentral/portal/templates/portal/help/faq.html, rnacentral/portal/templates/portal/help/text-search.html, rnacentral/portal/templates/portal/homepage.html, rnacentral/portal/templates/portal/training.html, rnacentral/portal/templates/portal/unique-rna-sequence.html
I made some changes in meta tags and descriptions to make the URS pages more distinct from each other and improve Google snippets.
=> Improve google search results

rnacentral/portal/static/js/rnaView.js, rnacentral/portal/templates/portal/unique-rna-sequence.html, rnacentral/rnacentral/urls.py, rnacentral/templates/robots-test.txt, rnacentral/templates/robots.txt
=> 183 improve google results

Dockerfile, README.md, rnacentral/portal/management/commands/ftp_exporters/md5.py, rnacentral/portal/management/commands/ftp_exporters/xrefs.py, rnacentral/requirements.txt, rnacentral/rnacentral/local_settings_default.py, rnacentral/scripts/env_template.sh
Not all dependencies are removed by this but I propose to merge this in `release-8` and continue removing the remaining Oracle bits.
=> Remove oracle dependency

rnacentral/portal/static/js/components/genome-browser/genoverse-utils.service.js, rnacentral/portal/static/js/components/sequence/sequence.module.js, rnacentral/portal/static/js/components/sequence/xrefs/xrefs.html, rnacentral/portal/templates/portal/sequence.html
- Genoverse shows up on RNA page
- Tooltip on Xrefs table's link to a transcript didn't refer to the source database - fixed that
=> 110 initials and sequence page redesign

rnacentral/apiv1/serializers.py, rnacentral/apiv1/urls.py, rnacentral/apiv1/views.py, rnacentral/portal/models/rna.py, rnacentral/portal/static/js/components/routes.service.js, rnacentral/portal/static/js/components/sequence/2d/2d.component.js, rnacentral/portal/static/js/components/sequence/sequence.module.js, rnacentral/portal/static/package.json, rnacentral/portal/templates/portal/base.html, rnacentral/portal/templates/portal/sequence.html
Examples:
2D present (GtRNAdb entry): http://localhost:8000/rna/URS00001F7668/137722
2D not present (not a GtRNAdb entry):
http://localhost:8000/rna/URS0000591E4F/3702
API call:
http://localhost:8000/api/v1/rna/URS00001F7668/2d/137722
=> Display 2d structures

rnacentral/portal/static/css/main.css, rnacentral/portal/static/js/app.js, rnacentral/portal/static/js/components/routes.service.js, rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.component.js, rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.html, rnacentral/portal/static/js/components/text-search/text-search.service.js, rnacentral/portal/static/package.json, rnacentral/portal/templates/portal/base.html
=> 265 length slider

rnacentral/apiv1/serializers.py, rnacentral/apiv1/urls.py, rnacentral/apiv1/views.py
Fixed retrieval of GenomeCoordinates of species that are not in RNAcentral species list (such as Felis catus).
=> 313 chromosome names

rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.component.js, rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.html, rnacentral/portal/static/js/components/text-search/text-search.service.js
Added sort options on top of results list.
=> 240 search sorting

rnacentral/portal/static/js/components/genome-browser/genoverse.component.js, rnacentral/portal/templates/portal/sequence.html, rnacentral/portal/views.py
FYI. Will merge and deploy later today.
=> Speed up sequence pages and hide aggressive JS alerts

rnacentral/apiv1/views.py
When given a species name, do `EnsemblAssembly.objects.get(ensembl_url=species)` and use taxid of this assembly to retrieve xrefs in GenomeLocations, GenomeMappings and overlaps/features.
Checked on:
- http://localhost:8000/api/v1/overlap/region/dictyostelium_discoideum/4:2766042-2769077
- http://localhost:8000/rna/URS00003BBB9E/352472
Might break E.coli strains. There might be multiple taxids for one assembly name, so it's possible that it won't cover all the taxids.
Might also break something like `canis_lupus_familiaris` or `gorilla_gorilla_gorilla` somewhere somehow.
=> Use ensembl_assembly to retrieve taxid in locations, mappings and features

rnacentral/apiv1/views.py
Not ready to merge yet - requires additional testing.
Fix #412
=> Aggregate rnc_locations by chromosome

rnacentral/apiv1/urls.py, rnacentral/apiv1/views.py, rnacentral/portal/static/css/main.css, rnacentral/portal/static/js/components/routes.service.js, rnacentral/portal/static/js/components/sequence/sequence.module.js
@blakesweeney could you please test this locally when you get a chance? I would like to keep test.rnacentral.org on the 2Ds branch for external collaborators.
Example page: http://localhost:8000/rna/URS00001AC666/7227
=> Display mature miRNA features

docker-compose.yml, jenkins/refresh-dev-vdb.jenkinsfile, jenkins/refresh-pub-vdbs.jenkinsfile, jenkins/refresh-tst-vdb.jenkinsfile, rnacentral/fabfile.py, rnacentral/portal/static/css/main.css, rnacentral/portal/static/js/app.js, rnacentral/portal/static/js/components/routes.service.js, rnacentral/portal/static/js/components/sequence-search/expert-database-tooltip-template.html, rnacentral/portal/static/js/components/sequence-search/sequence-search.module.js, rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.html, rnacentral/portal/templates/portal/base.html, rnacentral/portal/templates/portal/header.html, rnacentral/portal/templates/portal/sequence.html, rnacentral/rnacentral/settings.py, rnacentral/rnacentral/urls.py, rnacentral/sequence_search/__init__.py, rnacentral/sequence_search/settings.py, rnacentral/sequence_search/templates/sequence-search.html, rnacentral/sequence_search/urls.py, rnacentral/sequence_search/views.py
Opening a PR to go through the code and keep this feature isolated from the rest of the changes for SAB or new release.
=> New sequence search

rnacentral/portal/config/svg_images.py, rnacentral/portal/templates/portal/homepage.html, rnacentral/portal/views.py
=> Add a new section about RNA secondary structure

rnacentral/export/views.py, rnacentral/requirements.txt, rnacentral/sequence_search/settings.py, rnacentral/sequence_search/templates/dashboard.html, rnacentral/sequence_search/tests.py, rnacentral/sequence_search/urls.py, rnacentral/sequence_search/views.py
Code related to the creation of the sequence search dashboard
=> Release 13 dashboard

rnacentral/apiv1/renderers.py, rnacentral/apiv1/views.py, rnacentral/portal/models/rna_precomputed.py, rnacentral/portal/models/xref.py
Changes to avoid errors with invalid entries
=> Fix errors

rnacentral/portal/config/expert_databases.py, rnacentral/portal/models/accession.py, rnacentral/portal/static/js/components/sequence/xrefs/xrefs.html, rnacentral/portal/templates/portal/about.html, rnacentral/portal/templates/portal/docs/faq.md
Update the links to the ENA’s new browser
=> Update the ENA URL

rnacentral/portal/templates/portal/r2dt.html, rnacentral/portal/urls.py, rnacentral/portal/views.py
Do not use the Github link if R2DT-Web is installed locally
=> R2DT-web dev

rnacentral/portal/templates/portal/base.html, rnacentral/portal/templates/portal/header.html, rnacentral/portal/templates/portal/homepage.html
Show message on all pages except the main page. Added link in the main menu
=> Show message about the survey

rnacentral/portal/templates/portal/docs/sequence-search-help.md, rnacentral/portal/templates/portal/sequence.html, rnacentral/sequence_search/templates/dashboard.html, rnacentral/sequence_search/views.py
- Add button to search for similar sequences in the sequence page
- Fix dashboard
- Update docs
=> Sequence search update

rnacentral/portal/templates/portal/license.html
This is required by the EBI. Adding it next to the license seems reasonable.
=> Add a small note about long term data preservation

rnacentral/portal/models/rna.py, rnacentral/portal/static/js/components/text-search/text-search-results/text-search-results.html
Updated text search results to hide warning icon on genes
=> Entry type genes

rnacentral/portal/models/rna.py
Reverting to using search index to get_secondary_structure to reduce load on database
=> Reverted get_secondary_structure to query search index instead of API
