RNAcentral/rnacentral-webcode

rnacentral/portal/templates/portal/unique-rna-sequence.html

The 2D and 3D tabs are not used for sequences. It looks better to not
display anything rather than put a message saying coming soon.

Remove extra tabs

---

rnacentral/portal/management/commands/xml_exporters/rna2xml.py

When doing a search by organism sometimes the first hits are all generic
misc RNA's. We don't want these at the top of search, despite being the
longest because other more specific RNA's are more interesting. Thus I
add a small (0.5) penalty to such RNA's. This small penalty will force
the generic results downward, while not placing them below things of a
similar priority. For example, human RNA will always be listed before
other species, but the miscRNA will not appear first.

Add penalty for generic types of RNA

---

rnacentral/export/schema/ensembl.json
rnacentral/portal/management/commands/ensembl_export.py
rnacentral/portal/tests/management/commands/ensembl_export_tests.py
rnacentral/requirements.txt

This is an implementation of the JSON export for ensembl as discussed in #91. We provide output for all active sequences in the database as well as providing xrefs for:
- GtRNAdb
- lncRNAdb
- miRBase
- Modomics
- PDBe
- SNOpy
- srPDB
- tmRNA
- Rfam (seed sequences only)
The code depends upon the pull request for #78, thus the reason this pull request is against that branch. I'm happy to close this and create a new pull request against master if that is better. 
This basically adds 1 new command for `manage.py` and some very minimal tests to support it. The script is meant to be run with the `--min` and `--max` options as it will take a very long time without it. I played a bit with a query like the one django creates and I found that using a max of ~100,000 is best as larger than that and …

Ensembl xref export

---

rnacentral/rnacentral/local_settings_default.py
rnacentral/rnacentral/settings.py

This app isn't needed in production. In addition, it appears to be causing crashes in production. Hopefully removing this will fix the crashes.

Remove the performance testing app

---

rnacentral/portal/models.py
rnacentral/portal/templates/portal/unique-rna-sequence.html
rnacentral/portal/tests/selenium_tests.py
rnacentral/portal/views.py

Google crawler complained about some slow loading pages, and many of them had the UI issue described in #115. 
I am hoping that page speed will improve after migrating to Postgres but the UI problem can be fixed now.
Examples:
* http://localhost:8000/rna/URS000042DDAB/1566162
* http://localhost:8000/rna/URS000042DDAB/
Fixes #115

115 xref filtering

---

rnacentral/portal/management/commands/import_hgnc.py
rnacentral/portal/tests/description_tests.py
rnacentral/portal/utils/descriptions/rule_method.py

The gene name is informative and often useful for searching. By putting it in the name it is easier to search and find interesting sequences.

Add logic to append gene name for HGNC #167

---

rnacentral/portal/tests/description_tests.py
rnacentral/portal/utils/descriptions/rule_method.py

This branch is based off the add-hgnc-gene-name-to-description branch as it is complementary to that work. We only store non-protein coding RNA so there is little reason to include the `(non-protein coding)` text in our descriptions. This adds a test and an example of stripping that text. I think this makes descriptions look nicer but is possibly unneeded. 
On the downside this could cause problems for external resources using our names in a context where protein coding genes are around. But I'm not sure how much we should worry about that.

Remove (non-protein coding) for description text

---

rnacentral/portal/management/commands/xml_export.py
rnacentral/portal/management/commands/xml_exporters/rna2xml.py

This corrects part 2 in #161. The issue was that before if the RNA type was 'antisense_RNA' then we would find another RNA type and index that too. This is not what we want to happen so now we don't do that. If we don't have a precomputed RNA type it then uses feature_type or ncrna_type as needed. 
The changes have 2 parts. First I rework the xml_export command to accept an optional list of upis (with the --upis option) or the standard --min/--max. I used this to debug and fix the issues. In doing so I flattened out the structure of code. I had a lot of trouble following all the nested functions.

Correct exported rna type

---

rnacentral/portal/migrations/0012_auto_20170818_1016.py
rnacentral/portal/models.py

As part of the GtRNAdb import we will be storing secondary structures.
This requires us to have a table to store the pairing information into
the database. This is a very simple table that will store the secondary
structure pairing information as a dot-bracket string. The secondary
structure is linked to an accession as the information comes from some
database. We allow for a single accession to have more than one
secondary structure, as this is possible. This does not contain any
information on the layout of the secondary structure (how to draw it) as
for now we will stick to something like forna to draw it.

Add table to store secondary structures

---

rnacentral/portal/tests/description_tests.py
rnacentral/portal/utils/descriptions/rule_method.py

This adds some logic to detect if a sequence has been assigned to several genes and if so use those gene names in the description. The idea is to show as many as possible and if there are too many just show (multiple genes). This works for HGNC and miRBase, where it will detect precursors. It can also compress a range of gene names like `5SRNA1, 5SRNA2, 5SRNA3` to `5SRNA1-3`. In cases where the gene name already contains a dash it will use `to` like `5SRNA1 to 3`.

Correct hgnc naming

---

rnacentral/portal/templates/portal/sequence.html

If we have a single Rfam match then the match should be allowed to take
up all the room. This is nice in cases where the GO term description is
long as this way it will not split into several lines unnecessarily. This
adds that functionality. Two examples are:
http://localhost:8000/rna/URS000080E226/274
and
http://localhost:8000/rna/URS00000478B7/9606
In the second there is a large space between the image and the text but
that is because that image is very narrow. Shrinking the space to the
text in that case makes the first case with a wide image look bad.
I've also added a with statement for the grouped hits as I end up using
it several times when detecting the classes.

Expand the Rfam classification when possible

---

rnacentral/portal/management/commands/update_coordinate_names.py
rnacentral/portal/management/commands/update_ensembl_genome_mapping.py
rnacentral/portal/migrations/0016_merge.py
rnacentral/portal/migrations/0017_auto_20171214_1138.py
rnacentral/portal/migrations/0018_auto_20171214_1524.py
rnacentral/portal/migrations/0019_auto_20171214_1538.py
rnacentral/portal/models/ensembl_assembly.py
rnacentral/portal/models/ensembl_insdc_mapping.py

This PR uses the Ensembl MySQL database to map more RNAcentral accessions to reference genomes. Almost 300,000 additional exons are mapped to reference genomes, mostly from NONCODE, Rfam, and ENA. ✨
- _ensembl_assembly_. Example data: 
```
GRCh38	GRCh38.p10	GCA_000001405.25	hg38	human	9606
UMD2	Turkey_2.01	GCA_000146605.1	melGal1 turkey	9103
```
Note that now we will have a reliable mapping between Ensembl and **UCSC** database names (e.g. melGal1).
- _ensembl_insdc_mapping_. Example data:
```
1	CM000410.1	2	OANA5
2	CM000412.1	4	OANA5
```
Now the _name_ field in the _rnc_coordinates_ table can be updated to `2` for all rows where `primary_accession` is `CM000410.1`.
`python manage.py update_ensembl_genome_mapping` will update _ensembl_assembly_ and _ensembl_insdc_mapping_ tables. The …

Map more sequences to reference genomes

---

rnacentral/portal/rfam_matches.py

There are some tRNA sequences that we create warnings for which we should not. For example:
A tRNA from HGNC found in mitochondria: http://localhost:8000/rna/URS000036D40A/9606
A tRNA in mitochondria, but not from HGNC: http://localhost:8000/rna/URS0000400378/59896
Basically this prevents warnings from happening, if a tRNA sequence has not Rfam matches and seems to occur in the mitochondria.

tRNA warnings improvements

---

Dockerfile-development

For some reason installing these pages later in the dockerfile causes it
to fail on my machine. Moving it to the front of the file seems to fix
this.

This moves where we install yum packages

---

rnacentral/portal/management/commands/import_hgnc.py

In some cases (25 to be exact) HGNC can tell us that a molecule is
stored in the mitochondria. In those we store that information. Most of
the location entry is stuff like `7q32.1`, which is a position on a
nuclear chromosome. This is a minor improvement but does make the HGNC
annotations consistent with other databases in these cases, as
previously all other databases would state the molecule is found in the
mitochondria.

Determine when sequences are mitochondrial

---

rnacentral/portal/static/js/components/sequence/go-annotations/go_annotations.component.js

A small change to how the GO annotation table is displayed. We want to place the more useful annotations at the top. This was suggested by Rachael. Her suggestions were:
> I would suggest, if possible, ordering the annotations by evidence code
with the experimental evidence codes taking priority (IDA, IMP, IPI, IGI,
IEP).
> 
> A few of the entries I’ve looked at have Inferred from Structural or
sequence similarity (ISS) annotations listed first, e.g. See
http://rnacentral.org/rna/URS00003768C5/9606.
ISS is a non-experimental evidence code that doesn’t convey as much weight
as an experimental code. See
http://geneontology.org/page/guide-go-evidence-codes; the first six are
the experimental evidence codes.
This should cover her suggested changes.

Try to improve go annotation table sorting

---

rnacentral/portal/tests/description_tests.py
rnacentral/portal/utils/descriptions/rule_method.py

The issue was that we did not add the tmRNA database to ordering list of possible databases. This lead to the rule method never being applied and thus the issue with the names.

Fixes #269

---

rnacentral/portal/templates/portal/homepage.html
rnacentral/portal/templates/portal/sequence.html

The JSON-LD passes validation (mostly, got 2 small errors because RNA is not defined in BioSchemas yet):
https://search.google.com/structured-data/testing-tool/u/0/

Add json-ld definitions for DataCatalog and DataRecord

---

rnacentral/apiv1/serializers.py
rnacentral/apiv1/urls.py
rnacentral/apiv1/views.py
rnacentral/portal/models/__init__.py
rnacentral/portal/models/ensembl_compara.py
rnacentral/portal/static/js/components/routes.service.js
rnacentral/portal/static/js/components/sequence/ensembl-compara/ensembl-compara.component.js
rnacentral/portal/static/js/components/sequence/ensembl-compara/ensembl-compara.html
rnacentral/portal/templates/portal/base.html
rnacentral/portal/templates/portal/sequence.html

**Features**
✅ links to Ensembl Compara tree
✅ paginates after 50 sequences
✅ identical sequences marked with a badge
**Examples**
- Many related sequences (supports pagination): http://localhost:8000/rna/URS0000001EB3/9606
- Only one related sequence: http://localhost:8000/rna/URS0000001A7A/9606
- No related sequences (nothing is shown): http://localhost:8000/rna/URS000075D95B/9606
⚠️ Do not merge until the production databases have the Compara tables ⚠️ 
@blakesweeney Please review on a local machine using the _TST_ database when you get a chance. Thanks!
Fixes #445, closes #342, and closes #32.

Display Ensembl Compara

---

rnacentral/portal/static/js/components/routes.service.js
rnacentral/portal/static/js/components/sequence-search/sequence-search.module.js
rnacentral/portal/templates/portal/docs/sequence-search-help.md
rnacentral/sequence_search/templates/sequence-search.html
rnacentral/sequence_search/urls.py
rnacentral/sequence_search/views.py

The sequence search UI has been updated to display the Rfam search results - thanks @carlosribas for adding Rfam to the search backend! 
[Single Rfam hit](https://test.rnacentral.org/sequence-search/?id=eb93d1d6-a987-47eb-8b1d-7d0f3c64788d&ordering=e_value):
[Several Rfam hits]():
[No Rfam hits](https://test.rnacentral.org/sequence-search/?id=9df599ec-a871-4f18-a774-336b35ebb434&ordering=e_value):
This section ☝️  looks differently as I don't want to waste space on the `Rfam classification` header.
If there is a problem checking Rfam job status, the following message is shown:
If there is a problem loading the results:
I added a new section about Rfam to the [sequence search docs](https://test.rnacentral.org/help/sequence-search).
I also made a few tweaks to the look and feel of the UI - …

Display Rfam results in sequence search

---

rnacentral/apiv1/urls.py

Allow access to the endpoint /api/v1/rna/<URS>/2d without specifying a taxid

Change rna-2d-species-specific endpoint

---

rnacentral/apiv1/views.py
rnacentral/portal/templates/portal/header.html
rnacentral/requirements.txt
rnacentral/rnacentral/settings.py
rnacentral/rnacentral/urls.py
rnacentral/rnacentral/utils/drf_spectacular.py

Hi!
First of all, thank you for putting this incredible resource out there!
I am new to RNAcentral and had some trouble navigating the API to see its capabilities. Since it is implemented using Django REST framework, I was certain that some automatic documentation could be done. So here's what I did:
- Implement [drf_spectacular](https://drf-spectacular.readthedocs.io/en/latest/readme.html), a tool for OpenAPI schema generation.
- Add /schema endpoint to return OpenAPI standard schema, so that it can be used in other applications (for me, it was Postman)
- Include endpoints with UIs to navigate and test the API. These are `/schema/redoc` and `schema/swagger-ui`. For instance, swagger-ui looks like this:
Happy to hear your comments and to edit the `/api` page with the new information if …

Improve API documentation

---

entrypoint.sh

The purpose of the PR is to solve the static file permission issue encountered when deploying rnacentral pods in prod. Going forward, deploy one replica of the rnacentral with the following commands:
helm install full-prod . --set rnacentralReplicas=1
helm upgrade --install full-prod . --set rnacentralReplicas=1
then scale up to eight:
kubectl scale deployment --replicas=7 rnacentral

Removed check for preexisting static files
